### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by lebdron** [MBoldyrev/sarajivi_tg_bot#2]
```
Nov 21 22:17:28 raspberrypi python3[6408]: 2020-11-21 22:17:28,844 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Nov 21 22:17:28 raspberrypi python3[6408]: Traceback (most recent call last):
Nov 21 22:17:28 raspberrypi python3[6408]:   File "/home/andrei/sarajivi/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 425, in process_update
Nov 21 22:17:28 raspberrypi python3[6408]:     handler.handle_update(update, self, check, context)
Nov 21 22:17:28 raspberrypi python3[6408]:   File "/home/andrei/sarajivi/lib/python3.8/site-packages/telegram/ext/handler.py", line 145, in handle_update
Nov 21 22:17:28 raspberrypi python3[6408]:     return self.callback(update, context)
Nov 21 22:17:28 raspberrypi python3[6408]:   File "bot.py", line 44, in handle_sara_text_msg
Nov 21 22:17:28 raspberrypi python3[6408]:     tags = list(gen_tags(update.message.text))
Nov 21 22:17:28 raspberrypi python3[6408]: TypeError: 'NoneType' object is not iterable
```

**Comment by lebdron** [comment]
After update, the top frame is
```
File "/home/andrei/sarajivi/sarajivi_tg_bot/bot.py", line 80, in handle_sara_text_msg
  maybe_tag = maybe_make_tag_reply(update.message.text)
```
And it happens with picture messages according to logs.
